### ISSUE TITLE
Add support for Radiosondes

### ISSUE THREAD

**Issue by MesutErdemir** [ianrenton/planesailing-server#24]
Hello,

Can you add tracking radiosondes by integrating radiosonde_auto_rx tool? It supports udp payload output. You can see this reference: https://github.com/projecthorus/radiosonde_auto_rx/wiki/Configuration-Settings#horus-udp-payload-summary-output

Thank you.

**Comment by ianrenton** [comment]
I have left my receiver running for a week and managed to get _one_ whole packet out of my receiver. I'm in a bad location for line of sight to and radiosonde launch sites and my poor quality coax probably isn't helping at UHF. I'll implement what I can based on the data I did receive, however I might be reliant on you for testing!

**Comment by ianrenton** [comment]
Change complete, please try it and let me know how you get on!

**Comment by MesutErdemir** [comment]
I will try it and write the result here. Thank you for your effort.

**Comment by MesutErdemir** [comment]
Hello,

I have tested it today and it works perfectly. Thanks.
